services:
  - name: manga-translator
    type: web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: uvicorn app.api.main:app --host 0.0.0.0 --port $PORT
    plan: free 
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11